// Package notification implements the outbox pattern (ADR-0008) for
// asynchronous email + LINE + SMS delivery.
//
// Flow:
//
//  1. Domain code (booking, subscription, ...) calls [Service.Enqueue*]
//     to insert a row in the `notifications` table.
//  2. The worker process calls [Service.DispatchPending] every ~60s,
//     which uses [Repository.ClaimBatch] with `FOR UPDATE SKIP LOCKED`
//     so multiple workers can scale horizontally without claiming the
//     same row twice.
//  3. The configured [Sender] (Resend, LINE, Log) ships the message.
//  4. On success: status → 'sent' + sent_at = NOW().
//     On render error: status → 'dead' immediately (retrying won't help).
//     On send error: status → 'queued' with exponential backoff
//     (2, 4, 8, 16, 32 minutes) up to MaxAttempts = 5, then 'dead'.
//
// Templates are bilingual TH/EN inline-string constants in templates.go,
// rendered with text/template (subject) + html/template (body). Plaintext
// is generated by stripping HTML tags from the body — adequate for
// transactional emails; multi-section newsletters would need a dedicated
// plaintext template.
//
// To avoid a circular dependency with the booking package, the
// [BookingInfo] struct is duplicated here rather than imported — callers
// build it from their own booking row at the point of state change. See
// `enqueue_hooks.go`.
//
// Senders are abstracted behind [Sender] (single method). Routing across
// channels is the concern of [CompositeSender], so the worker holds a
// single Sender reference regardless of how many channels are configured.
package notification
